version: "3"
services:
  nginx-eureka:
    image: eipwork/nginx:eureka
    ports:
      - "8000:80"
    environment:
      eureka.serviceUrl.default: http://monitor-eureka/eureka
      ENABLE_EUREKA_CLIENT: "true"