FROM centos:7.6.1810


ADD docker/jdk-8u202-linux-x64.tar.gz /var/lib/
ADD docker/pinpoint-agent-1.8.4.tar.gz /pinpoint-agent
COPY docker/config-pinpoint-agent.sh /config-pinpoint-agent.sh
COPY docker/entrypoint.sh /entrypoint.sh

ENV JAVA_HOME /var/lib/jdk1.8.0_202/
ENV PATH $PATH:/var/lib/jdk1.8.0_202/bin/
ENV PINPOINT_VERSION=1.8.4
ENV PINPOINT_COLLECTOR_IP=monitor-pinpoint-collector
ENV PINPOINT_COLLECTOR_TCP_PORT=9994
ENV PINPOINT_COLLECTOR_STAT_PORT=9995
ENV PINPOINT_COLLECTOR_SPAN_PORT=9996
# Set sampling rate. If you set it to N, 1 out of N transaction will be sampled.
ENV PINPOINT_PROFILER_SAMPLING_RATE=1
ENV PINPOINT_AGENT_DEBUG_LEVEL=INFO

ENV SENTINEL_IP=monitor-sentinel
ENV SENTINEL_PORT=9701


# 配置时区
ENV TIME_ZONE Asia/Shanghai
RUN echo "${TIME_ZONE}" > /etc/timezone \ 
  && ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime \
  && chmod +x /config-pinpoint-agent.sh \
  && chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]